spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: mayao666
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.mayao.entity

server:
  port: 8081
